services:
  foundation:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-cajal}/${IMAGE_NAME:-foundation}:${IMAGE_TAG:-latest}
    runtime: nvidia
    env_file: .env
    ports:
      - "${JUPYTER_HOST:-0.0.0.0}:${JUPYTER_HOST_PORT:-8888}:8888"
    volumes:
      - ..:/workspace/foundation
      - /etc/localtime:/etc/localtime:ro
      - /mnt/scratch09/:/mnt/scratch09/
      - /mnt/scratch09/scratch09/foundation/external/:/external
      - /mnt/dj-stor01/:/mnt/dj-stor01/
    entrypoint:
      [
        "/bin/bash", "-c",
        "set -e && \
         pip install git+https://github.com/cajal/djutils.git@v0.0.1 && \
         pip install git+https://github.com/cajal/fnn && \
         pip install -e /workspace/foundation && \
         jupyter lab \
           --ip=0.0.0.0 \
           --port=8888 \
           --IdentityProvider.token=$$JUPYTER_TOKEN \
           --ServerApp.allow_root=True \
           --no-browser"
      ]
    working_dir: /workspace/foundation/demos
    ipc: host
  foundation-cpu:
    extends: foundation
    runtime: runc
